import "@css/font-awesome-pro.css";
import "@css/plugin.css";
import "@css/responsive.css";
import "@css/scroll_top.css";
import "@css/spacing.css";
import "@css/style.css";
import "@istiIcon/style.css";
import "../styles/social-links.css";
import { Poppins, Spline_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import SocialLinksWidget from '../components/widgets/SocialLinks';
import dynamic from 'next/dynamic';

const ChatWidget = dynamic(() => import('../components/widgets/ChatWidget'), { ssr: false });

export const metadata = {
  title: "Isti Personal Portfolio React NextJS Template",
  description: "Generated by isti Personal Portfolio React NextJS Template",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--secondaryFont",
  display: "swap",
});
const splineSans = Spline_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--bodyFont",
  display: "swap",
});

const fontFamily = `${poppins.variable} ${splineSans.variable}`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontFamily}>
        {children}
        <SocialLinksWidget />
        <ToastContainer />
        <ChatWidget />
      </body>
    </html>
  );
}
